"""add specimen disposal batches

Revision ID: 0681b9ac2cac
Revises: 31137d73159c
Create Date: 2026-08-24 20:34:39.406790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0681b9ac2cac'
down_revision: Union[str, Sequence[str], None] = '31137d73159c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specimen_disposal_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_no', sa.String(length=20), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='PRINTED', nullable=False),
    sa.Column('disposal_method', sa.String(length=200), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('printed_by_id', sa.Integer(), nullable=True),
    sa.Column('printed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('disposer_id', sa.Integer(), nullable=True),
    sa.Column('verifier_id', sa.Integer(), nullable=True),
    sa.Column('approver_id', sa.Integer(), nullable=True),
    sa.Column('disposer_name', sa.String(length=200), nullable=True),
    sa.Column('verifier_name', sa.String(length=200), nullable=True),
    sa.Column('approver_name', sa.String(length=200), nullable=True),
    sa.Column('disposed_at', sa.DateTime(), nullable=True),
    sa.Column('disposed_by_id', sa.Integer(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_by_id', sa.Integer(), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['cancelled_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['disposed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['disposer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['printed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['verifier_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_specimen_disposal_batches_batch_no'), 'specimen_disposal_batches', ['batch_no'], unique=True)
    op.create_index(op.f('ix_specimen_disposal_batches_id'), 'specimen_disposal_batches', ['id'], unique=False)
    op.create_table('specimen_disposal_batch_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('container_snapshot', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['specimen_disposal_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['case_id'], ['surgical_cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'case_id', name='uq_disposal_batch_case')
    )
    op.create_index('idx_disposal_item_case', 'specimen_disposal_batch_items', ['case_id'], unique=False)
    op.create_index(op.f('ix_specimen_disposal_batch_items_id'), 'specimen_disposal_batch_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_specimen_disposal_batch_items_id'), table_name='specimen_disposal_batch_items')
    op.drop_index('idx_disposal_item_case', table_name='specimen_disposal_batch_items')
    op.drop_table('specimen_disposal_batch_items')
    op.drop_index(op.f('ix_specimen_disposal_batches_id'), table_name='specimen_disposal_batches')
    op.drop_index(op.f('ix_specimen_disposal_batches_batch_no'), table_name='specimen_disposal_batches')
    op.drop_table('specimen_disposal_batches')
    # ### end Alembic commands ###
