"""add requires_volume to specimen_templates

Revision ID: 06cb31f5e846
Revises: 8b64d0a60166
Create Date: 2026-07-03 22:20:57.564577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06cb31f5e846'
down_revision: Union[str, Sequence[str], None] = '8b64d0a60166'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specimen_templates', sa.Column('requires_volume', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('specimen_templates', 'requires_volume')
    # ### end Alembic commands ###
