"""add consult pdf approval and thumbnail snapshot columns

Revision ID: 1638baeb40cc
Revises: a3f9c1d2e5b7
Create Date: 2026-07-20 22:06:47.686760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1638baeb40cc'
down_revision: Union[str, Sequence[str], None] = 'a3f9c1d2e5b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surgical_cases', sa.Column('consult_pdf_approved_by_id', sa.Integer(), nullable=True))
    op.add_column('surgical_cases', sa.Column('consult_pdf_approved_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'surgical_cases', 'users', ['consult_pdf_approved_by_id'], ['id'])
    op.add_column('surgical_reports', sa.Column('consult_pdf_thumbnail_snapshot', sa.Text(), nullable=True))
    op.add_column('surgical_reports', sa.Column('consult_pdf_approved_by_snapshot', sa.String(), nullable=True))
    op.add_column('surgical_reports', sa.Column('consult_pdf_approved_at_snapshot', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surgical_reports', 'consult_pdf_approved_at_snapshot')
    op.drop_column('surgical_reports', 'consult_pdf_approved_by_snapshot')
    op.drop_column('surgical_reports', 'consult_pdf_thumbnail_snapshot')
    op.drop_constraint(None, 'surgical_cases', type_='foreignkey')
    op.drop_column('surgical_cases', 'consult_pdf_approved_at')
    op.drop_column('surgical_cases', 'consult_pdf_approved_by_id')
    # ### end Alembic commands ###
