"""add lab_code to system_settings for slide label namespace

Revision ID: 1afed0bae4a7
Revises: 8f4f801b4e2c
Create Date: 2026-10-08 20:51:17.187583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1afed0bae4a7'
down_revision: Union[str, Sequence[str], None] = '8f4f801b4e2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_settings', sa.Column('lab_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_settings', 'lab_code')
    # ### end Alembic commands ###
