"""add cyto_path_correlations and enable_cyto_path_qc

Revision ID: 2c4c405161f6
Revises: be59b30390b5
Create Date: 2026-08-28 15:02:44.542309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c4c405161f6'
down_revision: Union[str, Sequence[str], None] = 'be59b30390b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cyto_path_correlations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_type', sa.String(length=10), nullable=False),
    sa.Column('gyne_case_id', sa.Integer(), nullable=True),
    sa.Column('nongyne_case_id', sa.Integer(), nullable=True),
    sa.Column('accession_no', sa.String(), nullable=True),
    sa.Column('cytotechnologist_id', sa.Integer(), nullable=True),
    sa.Column('screening_diagnosis', sa.Text(), nullable=True),
    sa.Column('screening_summary', sa.Text(), nullable=True),
    sa.Column('screening_flags', sa.JSON(), nullable=True),
    sa.Column('screened_at', sa.DateTime(), nullable=True),
    sa.Column('pathologist_id', sa.Integer(), nullable=True),
    sa.Column('final_diagnosis', sa.Text(), nullable=True),
    sa.Column('final_summary', sa.Text(), nullable=True),
    sa.Column('final_flags', sa.JSON(), nullable=True),
    sa.Column('signed_out_at', sa.DateTime(), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=True),
    sa.Column('auto_result', sa.String(length=20), nullable=True, comment='hint only: identical | changed'),
    sa.Column('result', sa.String(length=30), nullable=True, comment='concordant | minor_discrepancy | major_discrepancy | not_applicable'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='awaiting_signout | pending_review | reviewed | no_screening_data'),
    sa.Column('discrepancy_category', sa.String(length=40), nullable=True, comment='interpretive | screening_miss | sampling | wording | other'),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cytotechnologist_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['gyne_case_id'], ['gyne_cytology_cases.id'], ),
    sa.ForeignKeyConstraint(['nongyne_case_id'], ['nongyne_cytology_cases.id'], ),
    sa.ForeignKeyConstraint(['pathologist_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_type', 'gyne_case_id', 'nongyne_case_id', name='uq_cyto_path_corr_case')
    )
    op.create_index(op.f('ix_cyto_path_correlations_accession_no'), 'cyto_path_correlations', ['accession_no'], unique=False)
    op.create_index(op.f('ix_cyto_path_correlations_case_type'), 'cyto_path_correlations', ['case_type'], unique=False)
    op.create_index(op.f('ix_cyto_path_correlations_cytotechnologist_id'), 'cyto_path_correlations', ['cytotechnologist_id'], unique=False)
    op.create_index(op.f('ix_cyto_path_correlations_gyne_case_id'), 'cyto_path_correlations', ['gyne_case_id'], unique=False)
    op.create_index(op.f('ix_cyto_path_correlations_id'), 'cyto_path_correlations', ['id'], unique=False)
    op.create_index(op.f('ix_cyto_path_correlations_nongyne_case_id'), 'cyto_path_correlations', ['nongyne_case_id'], unique=False)
    op.create_index(op.f('ix_cyto_path_correlations_pathologist_id'), 'cyto_path_correlations', ['pathologist_id'], unique=False)
    op.create_index(op.f('ix_cyto_path_correlations_signed_out_at'), 'cyto_path_correlations', ['signed_out_at'], unique=False)
    op.create_index(op.f('ix_cyto_path_correlations_status'), 'cyto_path_correlations', ['status'], unique=False)
    op.add_column('system_settings', sa.Column('enable_cyto_path_qc', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_settings', 'enable_cyto_path_qc')
    op.drop_index(op.f('ix_cyto_path_correlations_status'), table_name='cyto_path_correlations')
    op.drop_index(op.f('ix_cyto_path_correlations_signed_out_at'), table_name='cyto_path_correlations')
    op.drop_index(op.f('ix_cyto_path_correlations_pathologist_id'), table_name='cyto_path_correlations')
    op.drop_index(op.f('ix_cyto_path_correlations_nongyne_case_id'), table_name='cyto_path_correlations')
    op.drop_index(op.f('ix_cyto_path_correlations_id'), table_name='cyto_path_correlations')
    op.drop_index(op.f('ix_cyto_path_correlations_gyne_case_id'), table_name='cyto_path_correlations')
    op.drop_index(op.f('ix_cyto_path_correlations_cytotechnologist_id'), table_name='cyto_path_correlations')
    op.drop_index(op.f('ix_cyto_path_correlations_case_type'), table_name='cyto_path_correlations')
    op.drop_index(op.f('ix_cyto_path_correlations_accession_no'), table_name='cyto_path_correlations')
    op.drop_table('cyto_path_correlations')
    # ### end Alembic commands ###
