"""add_nongyne_cyto_reports_table

Revision ID: 2f046bc6011f
Revises: 94fff18ad131
Create Date: 2026-05-08 11:51:11.150855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f046bc6011f'
down_revision: Union[str, Sequence[str], None] = '94fff18ad131'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nongyne_cyto_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('accession_no', sa.String(), nullable=True),
    sa.Column('patient_title', sa.String(), nullable=True),
    sa.Column('patient_name', sa.String(), nullable=True),
    sa.Column('patient_hn', sa.String(), nullable=True),
    sa.Column('patient_cid', sa.String(), nullable=True),
    sa.Column('patient_birth_date', sa.DateTime(), nullable=True),
    sa.Column('patient_age', sa.Integer(), nullable=True),
    sa.Column('patient_gender', sa.String(), nullable=True),
    sa.Column('hospital_name', sa.String(), nullable=True),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('department_name', sa.String(), nullable=True),
    sa.Column('clinician_name', sa.String(), nullable=True),
    sa.Column('clinical_history_snapshot', sa.Text(), nullable=True),
    sa.Column('specimen_type', sa.String(), nullable=True),
    sa.Column('collection_site', sa.String(), nullable=True),
    sa.Column('microscopic_description', sa.Text(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('has_malignancy', sa.Boolean(), nullable=False),
    sa.Column('report_type', sa.Enum('FINAL', 'ADDENDUM', 'CORRECTED', 'REVISED', name='nongynereporttype'), nullable=False),
    sa.Column('pathologist_id', sa.Integer(), nullable=True),
    sa.Column('pathologist_name', sa.String(), nullable=True),
    sa.Column('cytotechnologist_id', sa.Integer(), nullable=True),
    sa.Column('cytotechnologist_name', sa.String(), nullable=True),
    sa.Column('signers_snapshot', sa.JSON(), nullable=True),
    sa.Column('lab_name_snapshot', sa.String(), nullable=True),
    sa.Column('lab_address_snapshot', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'PUBLISHED', 'CANCELLED', name='nongynereportstatus'), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('reported_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['nongyne_cytology_cases.id'], ),
    sa.ForeignKeyConstraint(['cytotechnologist_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pathologist_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nongyne_cyto_reports_accession_no'), 'nongyne_cyto_reports', ['accession_no'], unique=False)
    op.create_index(op.f('ix_nongyne_cyto_reports_has_malignancy'), 'nongyne_cyto_reports', ['has_malignancy'], unique=False)
    op.create_index(op.f('ix_nongyne_cyto_reports_hospital_id'), 'nongyne_cyto_reports', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_nongyne_cyto_reports_id'), 'nongyne_cyto_reports', ['id'], unique=False)
    op.create_index(op.f('ix_nongyne_cyto_reports_patient_cid'), 'nongyne_cyto_reports', ['patient_cid'], unique=False)
    op.create_index(op.f('ix_nongyne_cyto_reports_patient_hn'), 'nongyne_cyto_reports', ['patient_hn'], unique=False)
    op.create_index(op.f('ix_nongyne_cyto_reports_patient_name'), 'nongyne_cyto_reports', ['patient_name'], unique=False)
    op.create_index(op.f('ix_nongyne_cyto_reports_reported_at'), 'nongyne_cyto_reports', ['reported_at'], unique=False)
    op.create_table('nongyne_report_signers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('agreement', sa.String(), nullable=True),
    sa.Column('agreement_note', sa.Text(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['nongyne_cyto_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nongyne_report_signers_id'), 'nongyne_report_signers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nongyne_report_signers_id'), table_name='nongyne_report_signers')
    op.drop_table('nongyne_report_signers')
    op.drop_index(op.f('ix_nongyne_cyto_reports_reported_at'), table_name='nongyne_cyto_reports')
    op.drop_index(op.f('ix_nongyne_cyto_reports_patient_name'), table_name='nongyne_cyto_reports')
    op.drop_index(op.f('ix_nongyne_cyto_reports_patient_hn'), table_name='nongyne_cyto_reports')
    op.drop_index(op.f('ix_nongyne_cyto_reports_patient_cid'), table_name='nongyne_cyto_reports')
    op.drop_index(op.f('ix_nongyne_cyto_reports_id'), table_name='nongyne_cyto_reports')
    op.drop_index(op.f('ix_nongyne_cyto_reports_hospital_id'), table_name='nongyne_cyto_reports')
    op.drop_index(op.f('ix_nongyne_cyto_reports_has_malignancy'), table_name='nongyne_cyto_reports')
    op.drop_index(op.f('ix_nongyne_cyto_reports_accession_no'), table_name='nongyne_cyto_reports')
    op.drop_table('nongyne_cyto_reports')
    # ### end Alembic commands ###
