"""add mfa_step_up_minutes to system settings

Revision ID: 31137d73159c
Revises: fe20f9e98627
Create Date: 2026-08-21 22:49:06.843024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31137d73159c'
down_revision: Union[str, Sequence[str], None] = 'fe20f9e98627'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_settings', sa.Column('mfa_step_up_minutes', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_settings', 'mfa_step_up_minutes')
    # ### end Alembic commands ###
