"""add nongyne specimen storage

Revision ID: 3ebce957f931
Revises: bbf647206034
Create Date: 2026-09-08 15:59:40.195259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ebce957f931'
down_revision: Union[str, Sequence[str], None] = 'bbf647206034'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nongyne_cytology_cases', sa.Column('specimen_storage_status', sa.String(), nullable=True))
    op.add_column('nongyne_cytology_cases', sa.Column('specimen_storage_container', sa.String(), nullable=True))
    op.add_column('nongyne_cytology_cases', sa.Column('specimen_storage_at', sa.DateTime(), nullable=True))
    op.add_column('nongyne_cytology_cases', sa.Column('specimen_storage_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_nongyne_cytology_cases_specimen_storage_by_id_users', 'nongyne_cytology_cases', 'users', ['specimen_storage_by_id'], ['id'])
    op.add_column('nongyne_specimen_disposal_batch_items', sa.Column('container_snapshot', sa.String(), nullable=True))
    # ### end Alembic commands ###

    # การทิ้งบังคับว่าต้องจัดเก็บก่อน (crud/nongyne_specimen_disposal_batch.create_batch)
    # เคสที่ออกผลแล้วและยังไม่ถูกทำลาย ของจริงอยู่ในตู้เย็นมาตลอดอยู่แล้ว เพียงแต่
    # ระบบยังไม่เคยมีที่ให้บันทึก — ถ้าไม่ backfill ตรงนี้ ทุกเคสที่ค้างอยู่ในคิวทิ้ง
    # จะกลายเป็นทิ้งไม่ได้ทันทีที่ deploy
    # container เว้นเป็น NULL ไว้ให้เจ้าหน้าที่มากรอกทีหลัง เพราะระบบไม่เคยรู้ว่าอยู่กล่องไหน
    op.execute(
        """
        UPDATE nongyne_cytology_cases
           SET specimen_storage_status = 'Stored'
         WHERE specimen_storage_status IS NULL
           AND status = 'published'
           AND discard_status = false
           AND is_cancelled = false
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nongyne_specimen_disposal_batch_items', 'container_snapshot')
    op.drop_constraint('fk_nongyne_cytology_cases_specimen_storage_by_id_users', 'nongyne_cytology_cases', type_='foreignkey')
    op.drop_column('nongyne_cytology_cases', 'specimen_storage_by_id')
    op.drop_column('nongyne_cytology_cases', 'specimen_storage_at')
    op.drop_column('nongyne_cytology_cases', 'specimen_storage_container')
    op.drop_column('nongyne_cytology_cases', 'specimen_storage_status')
    # ### end Alembic commands ###
