"""drop outlab_report_pdf_path from gyne cytology case

Revision ID: 42952d2e9ee4
Revises: ad612711c68a
Create Date: 2026-07-05 12:14:39.027822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42952d2e9ee4'
down_revision: Union[str, Sequence[str], None] = 'ad612711c68a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gyne_cytology_cases', 'outlab_report_pdf_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gyne_cytology_cases', sa.Column('outlab_report_pdf_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
