"""add stain to cytology case images

Revision ID: 465685500204
Revises: 2c4c405161f6
Create Date: 2026-08-31 20:44:38.582075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '465685500204'
down_revision: Union[str, Sequence[str], None] = '2c4c405161f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gyne_case_images', sa.Column('stain', sa.String(), nullable=True))
    op.add_column('nongyne_case_images', sa.Column('stain', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nongyne_case_images', 'stain')
    op.drop_column('gyne_case_images', 'stain')
    # ### end Alembic commands ###
