"""add system_configs table

Revision ID: 471992f2aa50
Revises: c3d4e5f6a7b8
Create Date: 2026-05-02 23:46:27.134342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '471992f2aa50'
down_revision: Union[str, Sequence[str], None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_configs',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_gyne_cytology_cases_consult_status'), 'gyne_cytology_cases', ['consult_status'], unique=False)
    op.create_index(op.f('ix_nongyne_cytology_cases_consult_status'), 'nongyne_cytology_cases', ['consult_status'], unique=False)
    op.create_index(op.f('ix_surgical_cases_consult_status'), 'surgical_cases', ['consult_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_surgical_cases_consult_status'), table_name='surgical_cases')
    op.drop_index(op.f('ix_nongyne_cytology_cases_consult_status'), table_name='nongyne_cytology_cases')
    op.drop_index(op.f('ix_gyne_cytology_cases_consult_status'), table_name='gyne_cytology_cases')
    op.drop_table('system_configs')
    # ### end Alembic commands ###
