"""add consult fields to nongyne cytology case

Revision ID: 47be7ba59d77
Revises: df6a2d115004
Create Date: 2026-07-04 12:56:21.034133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47be7ba59d77'
down_revision: Union[str, Sequence[str], None] = 'df6a2d115004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nongyne_cytology_cases', sa.Column('pending_reason', sa.Text(), nullable=True))
    op.add_column('nongyne_cytology_cases', sa.Column('consult_reason', sa.Text(), nullable=True))
    op.add_column('nongyne_cytology_cases', sa.Column('consult_report_out_at', sa.DateTime(), nullable=True))
    op.add_column('nongyne_cytology_cases', sa.Column('consult_pdf_received_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nongyne_cytology_cases', 'consult_pdf_received_at')
    op.drop_column('nongyne_cytology_cases', 'consult_report_out_at')
    op.drop_column('nongyne_cytology_cases', 'consult_reason')
    op.drop_column('nongyne_cytology_cases', 'pending_reason')
    # ### end Alembic commands ###
