"""drop MFA backup codes

Revision ID: 4d5dc1741ace
Revises: c6c46a6a56e1
Create Date: 2026-08-19 15:51:06.763386

The lab chose administrator-verified reset over self-service recovery codes.
The reasoning was that a printed sheet of codes ends up somewhere that defeats
the point of having a second factor — a drawer, a wallet, taped to the monitor
— and that a phone call to someone who can verify who is asking is a stronger
check than a piece of paper anybody could have picked up.

The trade accepted with it: recovery now depends on a person being reachable.
See POST /users/{id}/mfa/reset and scripts/reset_mfa.py for the two routes that
replace it.

No data is lost by this in practice — nothing had enrolled in production yet.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d5dc1741ace'
down_revision: Union[str, Sequence[str], None] = 'c6c46a6a56e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_mfa_backup_codes_id'), table_name='user_mfa_backup_codes')
    op.drop_index(op.f('ix_user_mfa_backup_codes_user_id'), table_name='user_mfa_backup_codes')
    op.drop_table('user_mfa_backup_codes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_mfa_backup_codes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('code_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_mfa_backup_codes_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_mfa_backup_codes_pkey'))
    )
    op.create_index(op.f('ix_user_mfa_backup_codes_user_id'), 'user_mfa_backup_codes', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_mfa_backup_codes_id'), 'user_mfa_backup_codes', ['id'], unique=False)
    # ### end Alembic commands ###
