"""drop_report_fk_constraints

Revision ID: 5704262b6dda
Revises: a3edc2f7ccf4
Create Date: 2026-06-22 00:26:12.000296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5704262b6dda'
down_revision: Union[str, Sequence[str], None] = 'a3edc2f7ccf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gyne_report_signers', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('gyne_report_signers_user_id_fkey'), 'gyne_report_signers', type_='foreignkey')
    op.alter_column('nongyne_report_signers', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('nongyne_report_signers_user_id_fkey'), 'nongyne_report_signers', type_='foreignkey')
    op.drop_constraint(op.f('report_signers_user_id_fkey'), 'report_signers', type_='foreignkey')
    op.alter_column('surgical_reports', 'hospital_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('surgical_reports_case_id_fkey'), 'surgical_reports', type_='foreignkey')
    op.drop_constraint(op.f('surgical_reports_approved_by_id_fkey'), 'surgical_reports', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('surgical_reports_approved_by_id_fkey'), 'surgical_reports', 'users', ['approved_by_id'], ['id'])
    op.create_foreign_key(op.f('surgical_reports_case_id_fkey'), 'surgical_reports', 'surgical_cases', ['case_id'], ['id'])
    op.alter_column('surgical_reports', 'hospital_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(op.f('report_signers_user_id_fkey'), 'report_signers', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('nongyne_report_signers_user_id_fkey'), 'nongyne_report_signers', 'users', ['user_id'], ['id'])
    op.alter_column('nongyne_report_signers', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(op.f('gyne_report_signers_user_id_fkey'), 'gyne_report_signers', 'users', ['user_id'], ['id'])
    op.alter_column('gyne_report_signers', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
