"""add_wsi_files_and_slide_links

Revision ID: 69750e1be875
Revises: 76ebca665242
Create Date: 2026-06-28 20:17:18.504389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69750e1be875'
down_revision: Union[str, Sequence[str], None] = '76ebca665242'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wsi_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('width_px', sa.Integer(), nullable=True),
    sa.Column('height_px', sa.Integer(), nullable=True),
    sa.Column('mpp_x', sa.Numeric(), nullable=True),
    sa.Column('mpp_y', sa.Numeric(), nullable=True),
    sa.Column('level_count', sa.Integer(), nullable=True),
    sa.Column('scanner_profile_id', sa.Integer(), nullable=True),
    sa.Column('parsed_accession', sa.String(), nullable=True),
    sa.Column('parsed_block', sa.String(), nullable=True),
    sa.Column('parse_confidence', sa.String(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scanner_profile_id'], ['wsi_scanner_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wsi_files_file_path'), 'wsi_files', ['file_path'], unique=True)
    op.create_index(op.f('ix_wsi_files_filename'), 'wsi_files', ['filename'], unique=False)
    op.create_index(op.f('ix_wsi_files_id'), 'wsi_files', ['id'], unique=False)
    op.create_index(op.f('ix_wsi_files_parsed_accession'), 'wsi_files', ['parsed_accession'], unique=False)
    op.create_table('wsi_slide_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wsi_file_id', sa.Integer(), nullable=False),
    sa.Column('surgical_block_id', sa.Integer(), nullable=False),
    sa.Column('stain_type', sa.String(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('link_method', sa.String(), nullable=True),
    sa.Column('link_confidence', sa.Numeric(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('linked_by_id', sa.Integer(), nullable=True),
    sa.Column('linked_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed_by_id', sa.Integer(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['confirmed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['linked_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['surgical_block_id'], ['surgical_blocks.id'], ),
    sa.ForeignKeyConstraint(['wsi_file_id'], ['wsi_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wsi_slide_links_id'), 'wsi_slide_links', ['id'], unique=False)
    op.create_index(op.f('ix_wsi_slide_links_status'), 'wsi_slide_links', ['status'], unique=False)
    op.create_index(op.f('ix_wsi_slide_links_surgical_block_id'), 'wsi_slide_links', ['surgical_block_id'], unique=False)
    op.create_index(op.f('ix_wsi_slide_links_wsi_file_id'), 'wsi_slide_links', ['wsi_file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wsi_slide_links_wsi_file_id'), table_name='wsi_slide_links')
    op.drop_index(op.f('ix_wsi_slide_links_surgical_block_id'), table_name='wsi_slide_links')
    op.drop_index(op.f('ix_wsi_slide_links_status'), table_name='wsi_slide_links')
    op.drop_index(op.f('ix_wsi_slide_links_id'), table_name='wsi_slide_links')
    op.drop_table('wsi_slide_links')
    op.drop_index(op.f('ix_wsi_files_parsed_accession'), table_name='wsi_files')
    op.drop_index(op.f('ix_wsi_files_id'), table_name='wsi_files')
    op.drop_index(op.f('ix_wsi_files_filename'), table_name='wsi_files')
    op.drop_index(op.f('ix_wsi_files_file_path'), table_name='wsi_files')
    op.drop_table('wsi_files')
    # ### end Alembic commands ###
