"""add_wsi_settings_and_scanner_profiles

Revision ID: 76ebca665242
Revises: fe0d079322f0
Create Date: 2026-06-28 00:59:05.912770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76ebca665242'
down_revision: Union[str, Sequence[str], None] = 'fe0d079322f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wsi_scanner_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('filename_pattern', sa.String(), nullable=False),
    sa.Column('file_extensions', sa.JSON(), nullable=False),
    sa.Column('separator', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wsi_scanner_profiles_id'), 'wsi_scanner_profiles', ['id'], unique=False)
    op.create_table('wsi_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_slug', sa.String(), nullable=True),
    sa.Column('wsi_root_path', sa.String(), nullable=True),
    sa.Column('default_scanner_profile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['default_scanner_profile_id'], ['wsi_scanner_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wsi_settings_hospital_slug'), 'wsi_settings', ['hospital_slug'], unique=True)
    op.create_index(op.f('ix_wsi_settings_id'), 'wsi_settings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wsi_settings_id'), table_name='wsi_settings')
    op.drop_index(op.f('ix_wsi_settings_hospital_slug'), table_name='wsi_settings')
    op.drop_table('wsi_settings')
    op.drop_index(op.f('ix_wsi_scanner_profiles_id'), table_name='wsi_scanner_profiles')
    op.drop_table('wsi_scanner_profiles')
    # ### end Alembic commands ###
