"""add molecular cases table

Revision ID: 84d42681d7e2
Revises: 1638baeb40cc
Create Date: 2026-07-21 10:49:19.520439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84d42681d7e2'
down_revision: Union[str, Sequence[str], None] = '1638baeb40cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('molecular_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accession_no', sa.String(), nullable=False, comment='M26-00001'),
    sa.Column('parent_case_id', sa.Integer(), nullable=False),
    sa.Column('stain_id', sa.Integer(), nullable=True),
    sa.Column('ap_test_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('is_outlab', sa.Boolean(), nullable=False),
    sa.Column('result_text', sa.Text(), nullable=True),
    sa.Column('outlab_pdf_path', sa.String(), nullable=True),
    sa.Column('outlab_pdf_received_at', sa.DateTime(), nullable=True),
    sa.Column('registrar_id', sa.Integer(), nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.Column('reported_by_id', sa.Integer(), nullable=True),
    sa.Column('reported_at', sa.DateTime(), nullable=True),
    sa.Column('is_cancelled', sa.Boolean(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_by_id', sa.Integer(), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ap_test_id'], ['anatomical_pathology_tests.id'], ),
    sa.ForeignKeyConstraint(['cancelled_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_case_id'], ['surgical_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registrar_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reported_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['stain_id'], ['surgical_block_stains.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_molecular_cases_accession_no'), 'molecular_cases', ['accession_no'], unique=True)
    op.create_index(op.f('ix_molecular_cases_id'), 'molecular_cases', ['id'], unique=False)
    op.create_index(op.f('ix_molecular_cases_is_cancelled'), 'molecular_cases', ['is_cancelled'], unique=False)
    op.create_index(op.f('ix_molecular_cases_parent_case_id'), 'molecular_cases', ['parent_case_id'], unique=False)
    op.create_index(op.f('ix_molecular_cases_stain_id'), 'molecular_cases', ['stain_id'], unique=False)
    op.create_index(op.f('ix_molecular_cases_status'), 'molecular_cases', ['status'], unique=False)
    op.add_column('system_settings', sa.Column('molecular_accession_prefix', sa.String(), nullable=False, server_default='M'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_settings', 'molecular_accession_prefix')
    op.drop_index(op.f('ix_molecular_cases_status'), table_name='molecular_cases')
    op.drop_index(op.f('ix_molecular_cases_stain_id'), table_name='molecular_cases')
    op.drop_index(op.f('ix_molecular_cases_parent_case_id'), table_name='molecular_cases')
    op.drop_index(op.f('ix_molecular_cases_is_cancelled'), table_name='molecular_cases')
    op.drop_index(op.f('ix_molecular_cases_id'), table_name='molecular_cases')
    op.drop_index(op.f('ix_molecular_cases_accession_no'), table_name='molecular_cases')
    op.drop_table('molecular_cases')
    # ### end Alembic commands ###
