"""add default_slide_count to specimen_templates

Revision ID: 84f7bcc32805
Revises: 47e85ad263ab
Create Date: 2026-07-03 21:41:26.326267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84f7bcc32805'
down_revision: Union[str, Sequence[str], None] = '47e85ad263ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specimen_templates', sa.Column('default_slide_count', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('specimen_templates', 'default_slide_count')
    # ### end Alembic commands ###
