"""add requires_slide_count to specimen_templates

Revision ID: 8b64d0a60166
Revises: 84f7bcc32805
Create Date: 2026-07-03 22:04:54.952922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b64d0a60166'
down_revision: Union[str, Sequence[str], None] = '84f7bcc32805'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specimen_templates', sa.Column('requires_slide_count', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('specimen_templates', 'requires_slide_count')
    # ### end Alembic commands ###
