"""add slides_only to specimen_templates

Revision ID: 8f4f801b4e2c
Revises: f4f817548bb9
Create Date: 2026-09-21 10:51:53.544677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f4f801b4e2c'
down_revision: Union[str, Sequence[str], None] = 'f4f817548bb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specimen_templates', sa.Column('slides_only', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('specimen_templates', 'slides_only')
    # ### end Alembic commands ###
