"""add_legacy_report_tables

Revision ID: 8fec99595172
Revises: 5704262b6dda
Create Date: 2026-06-22 01:55:10.235074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fec99595172'
down_revision: Union[str, Sequence[str], None] = '5704262b6dda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legacy_gyne_cyto_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('accession_no', sa.String(), nullable=True),
    sa.Column('patient_title', sa.String(), nullable=True),
    sa.Column('patient_name', sa.String(), nullable=True),
    sa.Column('patient_ln', sa.String(), nullable=True),
    sa.Column('patient_hn', sa.String(), nullable=True),
    sa.Column('patient_cid', sa.String(), nullable=True),
    sa.Column('patient_birth_date', sa.DateTime(), nullable=True),
    sa.Column('patient_age', sa.Integer(), nullable=True),
    sa.Column('patient_gender', sa.String(), nullable=True),
    sa.Column('hospital_name', sa.String(), nullable=True),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('department_name', sa.String(), nullable=True),
    sa.Column('clinician_name', sa.String(), nullable=True),
    sa.Column('adequacy_text', sa.String(), nullable=True),
    sa.Column('endocervical_status_text', sa.String(), nullable=True),
    sa.Column('quality_text', sa.String(), nullable=True),
    sa.Column('category_1_text', sa.String(), nullable=True),
    sa.Column('category_2_text', sa.String(), nullable=True),
    sa.Column('interpretation', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('signers_snapshot', sa.JSON(), nullable=True),
    sa.Column('report_type', sa.String(), nullable=True),
    sa.Column('pathologist_name', sa.String(), nullable=True),
    sa.Column('cytotechnologist_name', sa.String(), nullable=True),
    sa.Column('lab_name_snapshot', sa.String(), nullable=True),
    sa.Column('lab_address_snapshot', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=True),
    sa.Column('is_print', sa.Boolean(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('reported_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legacy_gyne_cyto_reports_accession_no'), 'legacy_gyne_cyto_reports', ['accession_no'], unique=False)
    op.create_index(op.f('ix_legacy_gyne_cyto_reports_id'), 'legacy_gyne_cyto_reports', ['id'], unique=False)
    op.create_index(op.f('ix_legacy_gyne_cyto_reports_patient_hn'), 'legacy_gyne_cyto_reports', ['patient_hn'], unique=False)
    op.create_index(op.f('ix_legacy_gyne_cyto_reports_patient_name'), 'legacy_gyne_cyto_reports', ['patient_name'], unique=False)
    op.create_index(op.f('ix_legacy_gyne_cyto_reports_reported_at'), 'legacy_gyne_cyto_reports', ['reported_at'], unique=False)
    op.create_table('legacy_nongyne_cyto_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('accession_no', sa.String(), nullable=True),
    sa.Column('patient_title', sa.String(), nullable=True),
    sa.Column('patient_name', sa.String(), nullable=True),
    sa.Column('patient_ln', sa.String(), nullable=True),
    sa.Column('patient_hn', sa.String(), nullable=True),
    sa.Column('patient_cid', sa.String(), nullable=True),
    sa.Column('patient_birth_date', sa.DateTime(), nullable=True),
    sa.Column('patient_age', sa.Integer(), nullable=True),
    sa.Column('patient_gender', sa.String(), nullable=True),
    sa.Column('hospital_name', sa.String(), nullable=True),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('department_name', sa.String(), nullable=True),
    sa.Column('clinician_name', sa.String(), nullable=True),
    sa.Column('clinical_history_snapshot', sa.Text(), nullable=True),
    sa.Column('clinical_diagnosis_snapshot', sa.Text(), nullable=True),
    sa.Column('specimen_type', sa.String(), nullable=True),
    sa.Column('collection_site', sa.String(), nullable=True),
    sa.Column('gross_description', sa.Text(), nullable=True),
    sa.Column('microscopic_description', sa.Text(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('has_malignancy', sa.Boolean(), nullable=True),
    sa.Column('signers_snapshot', sa.JSON(), nullable=True),
    sa.Column('report_type', sa.String(), nullable=True),
    sa.Column('pathologist_name', sa.String(), nullable=True),
    sa.Column('cytotechnologist_name', sa.String(), nullable=True),
    sa.Column('lab_name_snapshot', sa.String(), nullable=True),
    sa.Column('lab_address_snapshot', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=True),
    sa.Column('is_pending', sa.Boolean(), nullable=True),
    sa.Column('pending_reason', sa.Text(), nullable=True),
    sa.Column('is_print', sa.Boolean(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('reported_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legacy_nongyne_cyto_reports_accession_no'), 'legacy_nongyne_cyto_reports', ['accession_no'], unique=False)
    op.create_index(op.f('ix_legacy_nongyne_cyto_reports_id'), 'legacy_nongyne_cyto_reports', ['id'], unique=False)
    op.create_index(op.f('ix_legacy_nongyne_cyto_reports_patient_hn'), 'legacy_nongyne_cyto_reports', ['patient_hn'], unique=False)
    op.create_index(op.f('ix_legacy_nongyne_cyto_reports_patient_name'), 'legacy_nongyne_cyto_reports', ['patient_name'], unique=False)
    op.create_index(op.f('ix_legacy_nongyne_cyto_reports_reported_at'), 'legacy_nongyne_cyto_reports', ['reported_at'], unique=False)
    op.create_table('legacy_surgical_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('accession_no', sa.String(), nullable=True),
    sa.Column('patient_title', sa.String(), nullable=True),
    sa.Column('patient_name', sa.String(), nullable=True),
    sa.Column('patient_ln', sa.String(), nullable=True),
    sa.Column('patient_hn', sa.String(), nullable=True),
    sa.Column('patient_cid', sa.String(), nullable=True),
    sa.Column('patient_birth_date', sa.DateTime(), nullable=True),
    sa.Column('patient_age', sa.Integer(), nullable=True),
    sa.Column('patient_age_display', sa.String(), nullable=True),
    sa.Column('patient_gender', sa.String(), nullable=True),
    sa.Column('collect_at', sa.DateTime(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.Column('hospital_name', sa.String(), nullable=True),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('department_name', sa.String(), nullable=True),
    sa.Column('clinician_name', sa.String(), nullable=True),
    sa.Column('has_malignancy', sa.Boolean(), nullable=True),
    sa.Column('has_critical', sa.Boolean(), nullable=True),
    sa.Column('is_pending', sa.Boolean(), nullable=True),
    sa.Column('pending_reason', sa.Text(), nullable=True),
    sa.Column('clinical_history_snapshot', sa.Text(), nullable=True),
    sa.Column('specimen_summary', sa.Text(), nullable=True),
    sa.Column('gross_description_summary', sa.Text(), nullable=True),
    sa.Column('submitted_sections_snapshot', sa.JSON(), nullable=True),
    sa.Column('diagnosis_summary', sa.Text(), nullable=True),
    sa.Column('microscopic_summary', sa.Text(), nullable=True),
    sa.Column('comment_summary', sa.Text(), nullable=True),
    sa.Column('signers_snapshot', sa.JSON(), nullable=True),
    sa.Column('report_type', sa.String(), nullable=True),
    sa.Column('pathologist_name', sa.String(), nullable=True),
    sa.Column('lab_name_th_snapshot', sa.String(), nullable=True),
    sa.Column('lab_name_en_snapshot', sa.String(), nullable=True),
    sa.Column('lab_address_snapshot', sa.Text(), nullable=True),
    sa.Column('report_footer_snapshot', sa.Text(), nullable=True),
    sa.Column('report_logo_url_snapshot', sa.String(), nullable=True),
    sa.Column('consult_pdf_path_snapshot', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('is_print', sa.Boolean(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('reported_at', sa.DateTime(), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approver_name_snapshot', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legacy_surgical_reports_accession_no'), 'legacy_surgical_reports', ['accession_no'], unique=False)
    op.create_index(op.f('ix_legacy_surgical_reports_id'), 'legacy_surgical_reports', ['id'], unique=False)
    op.create_index(op.f('ix_legacy_surgical_reports_patient_hn'), 'legacy_surgical_reports', ['patient_hn'], unique=False)
    op.create_index(op.f('ix_legacy_surgical_reports_patient_name'), 'legacy_surgical_reports', ['patient_name'], unique=False)
    op.create_index(op.f('ix_legacy_surgical_reports_reported_at'), 'legacy_surgical_reports', ['reported_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_legacy_surgical_reports_reported_at'), table_name='legacy_surgical_reports')
    op.drop_index(op.f('ix_legacy_surgical_reports_patient_name'), table_name='legacy_surgical_reports')
    op.drop_index(op.f('ix_legacy_surgical_reports_patient_hn'), table_name='legacy_surgical_reports')
    op.drop_index(op.f('ix_legacy_surgical_reports_id'), table_name='legacy_surgical_reports')
    op.drop_index(op.f('ix_legacy_surgical_reports_accession_no'), table_name='legacy_surgical_reports')
    op.drop_table('legacy_surgical_reports')
    op.drop_index(op.f('ix_legacy_nongyne_cyto_reports_reported_at'), table_name='legacy_nongyne_cyto_reports')
    op.drop_index(op.f('ix_legacy_nongyne_cyto_reports_patient_name'), table_name='legacy_nongyne_cyto_reports')
    op.drop_index(op.f('ix_legacy_nongyne_cyto_reports_patient_hn'), table_name='legacy_nongyne_cyto_reports')
    op.drop_index(op.f('ix_legacy_nongyne_cyto_reports_id'), table_name='legacy_nongyne_cyto_reports')
    op.drop_index(op.f('ix_legacy_nongyne_cyto_reports_accession_no'), table_name='legacy_nongyne_cyto_reports')
    op.drop_table('legacy_nongyne_cyto_reports')
    op.drop_index(op.f('ix_legacy_gyne_cyto_reports_reported_at'), table_name='legacy_gyne_cyto_reports')
    op.drop_index(op.f('ix_legacy_gyne_cyto_reports_patient_name'), table_name='legacy_gyne_cyto_reports')
    op.drop_index(op.f('ix_legacy_gyne_cyto_reports_patient_hn'), table_name='legacy_gyne_cyto_reports')
    op.drop_index(op.f('ix_legacy_gyne_cyto_reports_id'), table_name='legacy_gyne_cyto_reports')
    op.drop_index(op.f('ix_legacy_gyne_cyto_reports_accession_no'), table_name='legacy_gyne_cyto_reports')
    op.drop_table('legacy_gyne_cyto_reports')
    # ### end Alembic commands ###
