"""add tumor_registries table

Revision ID: 9ad34352d322
Revises: 1b257432826a
Create Date: 2026-06-25 14:57:13.306862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ad34352d322'
down_revision: Union[str, Sequence[str], None] = '1b257432826a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tumor_registries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('surgical_case_id', sa.Integer(), nullable=False),
    sa.Column('topography_code', sa.String(), nullable=True),
    sa.Column('topography_desc', sa.String(), nullable=True),
    sa.Column('morphology_code', sa.String(), nullable=True),
    sa.Column('morphology_desc', sa.String(), nullable=True),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('pt', sa.String(), nullable=True),
    sa.Column('pn', sa.String(), nullable=True),
    sa.Column('pm', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['surgical_case_id'], ['surgical_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tumor_registries_id'), 'tumor_registries', ['id'], unique=False)
    op.create_index(op.f('ix_tumor_registries_surgical_case_id'), 'tumor_registries', ['surgical_case_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tumor_registries_surgical_case_id'), table_name='tumor_registries')
    op.drop_index(op.f('ix_tumor_registries_id'), table_name='tumor_registries')
    op.drop_table('tumor_registries')
    # ### end Alembic commands ###
