"""add cancellation fields to nongyne cytology case

Revision ID: a0a0614438c3
Revises: 875ede2a743d
Create Date: 2026-07-02 14:43:56.979024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0a0614438c3'
down_revision: Union[str, Sequence[str], None] = '875ede2a743d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nongyne_cytology_cases', sa.Column('is_cancelled', sa.Boolean(), nullable=True))
    op.add_column('nongyne_cytology_cases', sa.Column('cancelled_at', sa.DateTime(), nullable=True))
    op.add_column('nongyne_cytology_cases', sa.Column('cancelled_by_id', sa.Integer(), nullable=True))
    op.add_column('nongyne_cytology_cases', sa.Column('cancel_reason', sa.Text(), nullable=True))
    op.create_index(op.f('ix_nongyne_cytology_cases_is_cancelled'), 'nongyne_cytology_cases', ['is_cancelled'], unique=False)
    op.create_foreign_key(None, 'nongyne_cytology_cases', 'users', ['cancelled_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'nongyne_cytology_cases', type_='foreignkey')
    op.drop_index(op.f('ix_nongyne_cytology_cases_is_cancelled'), table_name='nongyne_cytology_cases')
    op.drop_column('nongyne_cytology_cases', 'cancel_reason')
    op.drop_column('nongyne_cytology_cases', 'cancelled_by_id')
    op.drop_column('nongyne_cytology_cases', 'cancelled_at')
    op.drop_column('nongyne_cytology_cases', 'is_cancelled')
    # ### end Alembic commands ###
