"""add clinical_diagnosis to gyne_cytology_cases

Revision ID: a7141ff51594
Revises: 
Create Date: 2026-03-18 23:20:04.862452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a7141ff51594'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_external_labs_id'), table_name='external_labs')
    op.drop_index(op.f('ix_external_labs_name'), table_name='external_labs')
    # Drop FK that references external_labs before dropping the table
    op.drop_constraint('anatomical_pathology_tests_outlab_id_fkey', 'anatomical_pathology_tests', type_='foreignkey')
    op.drop_table('external_labs')
    op.drop_constraint(op.f('block_storage_runs_run_no_key'), 'block_storage_runs', type_='unique')
    op.drop_index(op.f('ix_block_storage_runs_run_no'), table_name='block_storage_runs')
    op.create_index(op.f('ix_block_storage_runs_run_no'), 'block_storage_runs', ['run_no'], unique=True)
    op.add_column('gyne_cytology_cases', sa.Column('clinical_diagnosis', sa.Text(), nullable=True))
    op.drop_index(op.f('idx_gyne_out_lab'), table_name='gyne_cytology_cases')
    op.create_index(op.f('ix_gyne_cytology_cases_is_out_lab_consult'), 'gyne_cytology_cases', ['is_out_lab_consult'], unique=False)
    op.alter_column('gyne_diagnoses', 'signers',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='List of pathologists (JSON)',
               existing_nullable=True)
    op.create_index(op.f('ix_gyne_report_signers_id'), 'gyne_report_signers', ['id'], unique=False)
    op.alter_column('gyne_stain_runs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_column('gyne_stain_runs', 'updated_at')
    op.alter_column('nongyne_cytology_cases', 'accession_no',
               existing_type=sa.VARCHAR(length=255),
               comment='N25-00001',
               existing_nullable=False)
    op.alter_column('nongyne_cytology_cases', 'is_satisfied_specimen',
               existing_type=sa.BOOLEAN(),
               comment='Specimen adequacy',
               existing_nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('nongyne_cytology_cases', 'stain_quality',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('poor', 'fair', 'good', name='qualityenum', native_enum=False),
               existing_nullable=True)
    op.alter_column('nongyne_cytology_cases', 'slide_clarity',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('poor', 'fair', 'good', name='qualityenum', native_enum=False),
               existing_nullable=True)
    op.drop_index(op.f('idx_nongyne_out_lab'), table_name='nongyne_cytology_cases')
    op.drop_constraint(op.f('nongyne_cytology_cases_accession_no_key'), 'nongyne_cytology_cases', type_='unique')
    op.drop_index(op.f('ix_nongyne_cytology_cases_accession_no'), table_name='nongyne_cytology_cases')
    op.create_index(op.f('ix_nongyne_cytology_cases_accession_no'), 'nongyne_cytology_cases', ['accession_no'], unique=True)
    op.create_index(op.f('ix_nongyne_cytology_cases_is_out_lab_consult'), 'nongyne_cytology_cases', ['is_out_lab_consult'], unique=False)
    op.alter_column('notification_channels', 'platform',
               existing_type=sa.VARCHAR(),
               comment='line, slack, discord, etc.',
               existing_nullable=False)
    op.alter_column('notification_channels', 'name',
               existing_type=sa.VARCHAR(),
               comment="Name to remember, e.g., 'Server Alert', 'Support Team'",
               existing_nullable=False)
    op.alter_column('notification_channels', 'credentials',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Stores channel specific configs like token or webhook url',
               existing_nullable=False)
    op.create_index(op.f('ix_notification_channels_id'), 'notification_channels', ['id'], unique=False)
    op.alter_column('notification_rules', 'message_template',
               existing_type=sa.TEXT(),
               comment='Template with {placeholders} filled by event data',
               existing_nullable=True)
    op.drop_constraint(op.f('slide_storage_runs_run_no_key'), 'slide_storage_runs', type_='unique')
    op.drop_index(op.f('ix_slide_storage_runs_run_no'), table_name='slide_storage_runs')
    op.create_index(op.f('ix_slide_storage_runs_run_no'), 'slide_storage_runs', ['run_no'], unique=True)
    op.drop_index(op.f('idx_surgical_out_lab'), table_name='surgical_cases')
    op.create_index(op.f('ix_surgical_cases_is_out_lab_consult'), 'surgical_cases', ['is_out_lab_consult'], unique=False)
    op.drop_constraint(op.f('surgical_outlab_runs_run_no_key'), 'surgical_outlab_runs', type_='unique')
    op.drop_index(op.f('ix_surgical_outlab_runs_run_no'), table_name='surgical_outlab_runs')
    op.create_index(op.f('ix_surgical_outlab_runs_run_no'), 'surgical_outlab_runs', ['run_no'], unique=True)
    op.drop_constraint(op.f('uq_system_settings_hospital_slug'), 'system_settings', type_='unique')
    op.create_index(op.f('ix_system_settings_hospital_slug'), 'system_settings', ['hospital_slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_settings_hospital_slug'), table_name='system_settings')
    op.create_unique_constraint(op.f('uq_system_settings_hospital_slug'), 'system_settings', ['hospital_slug'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_surgical_outlab_runs_run_no'), table_name='surgical_outlab_runs')
    op.create_index(op.f('ix_surgical_outlab_runs_run_no'), 'surgical_outlab_runs', ['run_no'], unique=False)
    op.create_unique_constraint(op.f('surgical_outlab_runs_run_no_key'), 'surgical_outlab_runs', ['run_no'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_surgical_cases_is_out_lab_consult'), table_name='surgical_cases')
    op.create_index(op.f('idx_surgical_out_lab'), 'surgical_cases', ['is_out_lab_consult'], unique=False)
    op.drop_index(op.f('ix_slide_storage_runs_run_no'), table_name='slide_storage_runs')
    op.create_index(op.f('ix_slide_storage_runs_run_no'), 'slide_storage_runs', ['run_no'], unique=False)
    op.create_unique_constraint(op.f('slide_storage_runs_run_no_key'), 'slide_storage_runs', ['run_no'], postgresql_nulls_not_distinct=False)
    op.alter_column('notification_rules', 'message_template',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Template with {placeholders} filled by event data',
               existing_nullable=True)
    op.drop_index(op.f('ix_notification_channels_id'), table_name='notification_channels')
    op.alter_column('notification_channels', 'credentials',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Stores channel specific configs like token or webhook url',
               existing_nullable=False)
    op.alter_column('notification_channels', 'name',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment="Name to remember, e.g., 'Server Alert', 'Support Team'",
               existing_nullable=False)
    op.alter_column('notification_channels', 'platform',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='line, slack, discord, etc.',
               existing_nullable=False)
    op.drop_index(op.f('ix_nongyne_cytology_cases_is_out_lab_consult'), table_name='nongyne_cytology_cases')
    op.drop_index(op.f('ix_nongyne_cytology_cases_accession_no'), table_name='nongyne_cytology_cases')
    op.create_index(op.f('ix_nongyne_cytology_cases_accession_no'), 'nongyne_cytology_cases', ['accession_no'], unique=False)
    op.create_unique_constraint(op.f('nongyne_cytology_cases_accession_no_key'), 'nongyne_cytology_cases', ['accession_no'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_nongyne_out_lab'), 'nongyne_cytology_cases', ['is_out_lab_consult'], unique=False)
    op.alter_column('nongyne_cytology_cases', 'slide_clarity',
               existing_type=sa.Enum('poor', 'fair', 'good', name='qualityenum', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('nongyne_cytology_cases', 'stain_quality',
               existing_type=sa.Enum('poor', 'fair', 'good', name='qualityenum', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('nongyne_cytology_cases', 'is_satisfied_specimen',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Specimen adequacy',
               existing_nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('nongyne_cytology_cases', 'accession_no',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='N25-00001',
               existing_nullable=False)
    op.add_column('gyne_stain_runs', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.alter_column('gyne_stain_runs', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_gyne_report_signers_id'), table_name='gyne_report_signers')
    op.alter_column('gyne_diagnoses', 'signers',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='List of pathologists (JSON)',
               existing_nullable=True)
    op.drop_index(op.f('ix_gyne_cytology_cases_is_out_lab_consult'), table_name='gyne_cytology_cases')
    op.create_index(op.f('idx_gyne_out_lab'), 'gyne_cytology_cases', ['is_out_lab_consult'], unique=False)
    op.drop_column('gyne_cytology_cases', 'clinical_diagnosis')
    op.drop_index(op.f('ix_block_storage_runs_run_no'), table_name='block_storage_runs')
    op.create_index(op.f('ix_block_storage_runs_run_no'), 'block_storage_runs', ['run_no'], unique=False)
    op.create_unique_constraint(op.f('block_storage_runs_run_no_key'), 'block_storage_runs', ['run_no'], postgresql_nulls_not_distinct=False)
    op.create_table('external_labs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('external_labs_pkey')),
    sa.UniqueConstraint('name', name=op.f('external_labs_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_external_labs_name'), 'external_labs', ['name'], unique=False)
    op.create_index(op.f('ix_external_labs_id'), 'external_labs', ['id'], unique=False)
    # ### end Alembic commands ###
