"""Add stain panels

Revision ID: a8a35626bbca
Revises: 5858b181cd57
Create Date: 2026-06-29 14:12:48.399559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8a35626bbca'
down_revision: Union[str, Sequence[str], None] = '5858b181cd57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stain_panels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stain_panels_category'), 'stain_panels', ['category'], unique=False)
    op.create_index(op.f('ix_stain_panels_id'), 'stain_panels', ['id'], unique=False)
    op.create_index(op.f('ix_stain_panels_name'), 'stain_panels', ['name'], unique=False)
    op.create_table('stain_panel_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stain_panel_id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stain_panel_id'], ['stain_panels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_id'], ['anatomical_pathology_tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stain_panel_items_id'), 'stain_panel_items', ['id'], unique=False)
    op.create_index(op.f('ix_stain_panel_items_stain_panel_id'), 'stain_panel_items', ['stain_panel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stain_panel_items_stain_panel_id'), table_name='stain_panel_items')
    op.drop_index(op.f('ix_stain_panel_items_id'), table_name='stain_panel_items')
    op.drop_table('stain_panel_items')
    op.drop_index(op.f('ix_stain_panels_name'), table_name='stain_panels')
    op.drop_index(op.f('ix_stain_panels_id'), table_name='stain_panels')
    op.drop_index(op.f('ix_stain_panels_category'), table_name='stain_panels')
    op.drop_table('stain_panels')
    # ### end Alembic commands ###
