"""add_clinical_diagnosis_snapshot_to_nongyne_cyto_reports

Revision ID: abb321ac60e2
Revises: 2f046bc6011f
Create Date: 2026-05-08 14:10:22.419647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abb321ac60e2'
down_revision: Union[str, Sequence[str], None] = '2f046bc6011f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nongyne_cyto_reports', sa.Column('clinical_diagnosis_snapshot', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nongyne_cyto_reports', 'clinical_diagnosis_snapshot')
    # ### end Alembic commands ###
