"""add consult fields to gyne cytology case

Revision ID: ad612711c68a
Revises: 47be7ba59d77
Create Date: 2026-07-04 20:22:51.880219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad612711c68a'
down_revision: Union[str, Sequence[str], None] = '47be7ba59d77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gyne_cytology_cases', sa.Column('consult_reason', sa.Text(), nullable=True))
    op.add_column('gyne_cytology_cases', sa.Column('consult_report_out_at', sa.DateTime(), nullable=True))
    op.add_column('gyne_cytology_cases', sa.Column('consult_pdf_received_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gyne_cytology_cases', 'consult_pdf_received_at')
    op.drop_column('gyne_cytology_cases', 'consult_report_out_at')
    op.drop_column('gyne_cytology_cases', 'consult_reason')
    # ### end Alembic commands ###
