"""add MFA method/backup-code tables and the MFA settings columns

Revision ID: b7e4a1c05f38
Revises: cb12a249b9b0
Create Date: 2026-08-18 16:34:02.115097

Schema only — nothing reads these yet, so applying this revision changes no
behaviour. The login path stays exactly as it is until the enrolment and
verification work lands on top.

Hand-written rather than autogenerated. `alembic upgrade head` against an
empty database did not get past creating `alembic_version` in roughly eight
minutes of solid CPU with no further SQL issued, which is what autogenerate
needs in order to diff. `alembic heads` returns instantly, so the revision
graph itself is fine; the cost appears to be in computing a full base..head
path across 152 revisions. Stamping a database at cb12a249b9b0 and upgrading
one step is instant, and that is how this revision was verified in both
directions.

Factors live in their own table rather than as columns on `users` on purpose:
one per-user secret can represent a single TOTP app and nothing else, whereas
WebAuthn is inherently multi-credential. See app/models/user_mfa.py.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'b7e4a1c05f38'
down_revision: Union[str, Sequence[str], None] = 'cb12a249b9b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        'user_mfa_methods',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('method_type', sa.String(length=20), nullable=False),
        sa.Column('label', sa.String(length=100), nullable=True),
        sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
        sa.Column('secret_enc', sa.Text(), nullable=True),
        sa.Column('last_used_step', sa.BigInteger(), nullable=True),
        sa.Column('credential_id', sa.LargeBinary(), nullable=True),
        sa.Column('public_key', sa.LargeBinary(), nullable=True),
        sa.Column('sign_count', sa.BigInteger(), nullable=True),
        sa.Column('transports', sa.JSON(), nullable=True),
        sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('credential_id'),
    )
    op.create_index(op.f('ix_user_mfa_methods_id'), 'user_mfa_methods', ['id'], unique=False)
    op.create_index(op.f('ix_user_mfa_methods_user_id'), 'user_mfa_methods', ['user_id'], unique=False)
    # Partial, so only the primary rows have to be distinct on user_id.
    op.create_index(
        'ux_user_mfa_methods_one_primary_per_user',
        'user_mfa_methods',
        ['user_id'],
        unique=True,
        postgresql_where=sa.text('is_primary'),
    )

    op.create_table(
        'user_mfa_backup_codes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('code_hash', sa.String(), nullable=False),
        sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_user_mfa_backup_codes_id'), 'user_mfa_backup_codes', ['id'], unique=False)
    op.create_index(op.f('ix_user_mfa_backup_codes_user_id'), 'user_mfa_backup_codes', ['user_id'], unique=False)

    op.add_column('users', sa.Column('mfa_enabled', sa.Boolean(), server_default='false', nullable=False))

    op.add_column('system_settings', sa.Column('mfa_enabled', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('system_settings', sa.Column('mfa_required_roles', sa.JSON(), nullable=True))
    op.add_column('system_settings', sa.Column('mfa_grace_period_days', sa.Integer(), server_default='7', nullable=False))
    op.add_column('system_settings', sa.Column('mfa_allowed_methods', sa.JSON(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('system_settings', 'mfa_allowed_methods')
    op.drop_column('system_settings', 'mfa_grace_period_days')
    op.drop_column('system_settings', 'mfa_required_roles')
    op.drop_column('system_settings', 'mfa_enabled')

    op.drop_column('users', 'mfa_enabled')

    op.drop_index(op.f('ix_user_mfa_backup_codes_user_id'), table_name='user_mfa_backup_codes')
    op.drop_index(op.f('ix_user_mfa_backup_codes_id'), table_name='user_mfa_backup_codes')
    op.drop_table('user_mfa_backup_codes')

    op.drop_index('ux_user_mfa_methods_one_primary_per_user', table_name='user_mfa_methods')
    op.drop_index(op.f('ix_user_mfa_methods_user_id'), table_name='user_mfa_methods')
    op.drop_index(op.f('ix_user_mfa_methods_id'), table_name='user_mfa_methods')
    op.drop_table('user_mfa_methods')
