"""add is_out_lab

Revision ID: b802d0d2203a
Revises: e7c5e362308e
Create Date: 2026-06-25 10:01:41.817484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b802d0d2203a'
down_revision: Union[str, Sequence[str], None] = 'e7c5e362308e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_tumor_registry_case'), table_name='tumor_registries')
    op.drop_index(op.f('ix_tumor_registries_id'), table_name='tumor_registries')
    op.drop_table('tumor_registries')
    op.alter_column('gyne_cytology_cases', 'is_out_lab',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('legacy_surgical_reports', 'report_logo_url_snapshot')
    op.create_index(op.f('ix_llm_profiles_id'), 'llm_profiles', ['id'], unique=False)
    op.alter_column('nongyne_cytology_cases', 'is_out_lab',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint(op.f('fk_system_settings_tumor_registry_llm_profile'), 'system_settings', type_='foreignkey')
    op.create_foreign_key(None, 'system_settings', 'llm_profiles', ['tumor_registry_llm_profile_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'system_settings', type_='foreignkey')
    op.create_foreign_key(op.f('fk_system_settings_tumor_registry_llm_profile'), 'system_settings', 'llm_profiles', ['tumor_registry_llm_profile_id'], ['id'], ondelete='SET NULL')
    op.alter_column('nongyne_cytology_cases', 'is_out_lab',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_llm_profiles_id'), table_name='llm_profiles')
    op.add_column('legacy_surgical_reports', sa.Column('report_logo_url_snapshot', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('gyne_cytology_cases', 'is_out_lab',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_table('tumor_registries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('surgical_case_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('topography_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('topography_desc', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('morphology_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('morphology_desc', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('grade', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pt', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pn', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pm', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('tumor_registries_created_by_id_fkey')),
    sa.ForeignKeyConstraint(['surgical_case_id'], ['surgical_cases.id'], name=op.f('tumor_registries_surgical_case_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tumor_registries_pkey'))
    )
    op.create_index(op.f('ix_tumor_registries_id'), 'tumor_registries', ['id'], unique=False)
    op.create_index(op.f('idx_tumor_registry_case'), 'tumor_registries', ['surgical_case_id'], unique=True)
    # ### end Alembic commands ###
