"""add surgical specimen_retention_days

Revision ID: bbf647206034
Revises: d6219a67897e
Create Date: 2026-09-05 22:12:37.092443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbf647206034'
down_revision: Union[str, Sequence[str], None] = 'd6219a67897e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_settings', sa.Column('specimen_retention_days', sa.Integer(), server_default='30', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_settings', 'specimen_retention_days')
    # ### end Alembic commands ###
