"""add specimen disposal doc no setting

Revision ID: be59b30390b5
Revises: 0681b9ac2cac
Create Date: 2026-08-25 10:19:44.425028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be59b30390b5'
down_revision: Union[str, Sequence[str], None] = '0681b9ac2cac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_settings', sa.Column('specimen_disposal_doc_no', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_settings', 'specimen_disposal_doc_no')
    # ### end Alembic commands ###
