"""add ihc marker extra fields

Revision ID: c3155e4b9ab8
Revises: 42952d2e9ee4
Create Date: 2026-07-05 14:31:22.028936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3155e4b9ab8'
down_revision: Union[str, Sequence[str], None] = '42952d2e9ee4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ihc_marker_extra_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ap_test_id', sa.Integer(), nullable=False),
    sa.Column('field_key', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('field_type', sa.String(length=10), nullable=False),
    sa.Column('numeric_unit', sa.String(length=20), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ap_test_id'], ['anatomical_pathology_tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ap_test_id', 'field_key', name='_ihc_marker_extra_field_key_uc')
    )
    op.create_index(op.f('ix_ihc_marker_extra_fields_ap_test_id'), 'ihc_marker_extra_fields', ['ap_test_id'], unique=False)
    op.create_index(op.f('ix_ihc_marker_extra_fields_id'), 'ihc_marker_extra_fields', ['id'], unique=False)
    op.create_table('ihc_marker_extra_field_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('option_label', sa.String(length=200), nullable=False),
    sa.Column('option_value', sa.String(length=200), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['ihc_marker_extra_fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ihc_marker_extra_field_options_field_id'), 'ihc_marker_extra_field_options', ['field_id'], unique=False)
    op.create_index(op.f('ix_ihc_marker_extra_field_options_id'), 'ihc_marker_extra_field_options', ['id'], unique=False)
    op.create_table('ihc_result_extra_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ihc_result_id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['ihc_marker_extra_fields.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ihc_result_id'], ['ihc_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ihc_result_id', 'field_id', name='_ihc_result_extra_field_uc')
    )
    op.create_index(op.f('ix_ihc_result_extra_values_field_id'), 'ihc_result_extra_values', ['field_id'], unique=False)
    op.create_index(op.f('ix_ihc_result_extra_values_id'), 'ihc_result_extra_values', ['id'], unique=False)
    op.create_index(op.f('ix_ihc_result_extra_values_ihc_result_id'), 'ihc_result_extra_values', ['ihc_result_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ihc_result_extra_values_ihc_result_id'), table_name='ihc_result_extra_values')
    op.drop_index(op.f('ix_ihc_result_extra_values_id'), table_name='ihc_result_extra_values')
    op.drop_index(op.f('ix_ihc_result_extra_values_field_id'), table_name='ihc_result_extra_values')
    op.drop_table('ihc_result_extra_values')
    op.drop_index(op.f('ix_ihc_marker_extra_field_options_id'), table_name='ihc_marker_extra_field_options')
    op.drop_index(op.f('ix_ihc_marker_extra_field_options_field_id'), table_name='ihc_marker_extra_field_options')
    op.drop_table('ihc_marker_extra_field_options')
    op.drop_index(op.f('ix_ihc_marker_extra_fields_id'), table_name='ihc_marker_extra_fields')
    op.drop_index(op.f('ix_ihc_marker_extra_fields_ap_test_id'), table_name='ihc_marker_extra_fields')
    op.drop_table('ihc_marker_extra_fields')
    # ### end Alembic commands ###
