"""add trusted devices for MFA

Revision ID: c6c46a6a56e1
Revises: b7e4a1c05f38
Create Date: 2026-08-19 11:02:30.845494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6c46a6a56e1'
down_revision: Union[str, Sequence[str], None] = 'b7e4a1c05f38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_trusted_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_trusted_devices_id'), 'user_trusted_devices', ['id'], unique=False)
    op.create_index(op.f('ix_user_trusted_devices_token_hash'), 'user_trusted_devices', ['token_hash'], unique=True)
    op.create_index(op.f('ix_user_trusted_devices_user_id'), 'user_trusted_devices', ['user_id'], unique=False)
    op.add_column('system_settings', sa.Column('mfa_trusted_device_days', sa.Integer(), server_default='14', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_settings', 'mfa_trusted_device_days')
    op.drop_index(op.f('ix_user_trusted_devices_user_id'), table_name='user_trusted_devices')
    op.drop_index(op.f('ix_user_trusted_devices_token_hash'), table_name='user_trusted_devices')
    op.drop_index(op.f('ix_user_trusted_devices_id'), table_name='user_trusted_devices')
    op.drop_table('user_trusted_devices')
    # ### end Alembic commands ###
