"""add_report_gen_llm_profile_id_to_system_settings

Revision ID: c9c753bbe9bb
Revises: 98c35d1d21ad
Create Date: 2026-06-26 14:06:51.345766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9c753bbe9bb'
down_revision: Union[str, Sequence[str], None] = '98c35d1d21ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_settings', sa.Column('report_gen_llm_profile_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'system_settings', 'llm_profiles', ['report_gen_llm_profile_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'system_settings', type_='foreignkey')
    op.drop_column('system_settings', 'report_gen_llm_profile_id')
    # ### end Alembic commands ###
