"""sync_prod

Revision ID: d1b84dda496e
Revises: 39169e78c3b8
Create Date: 2026-06-25 11:57:44.201024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd1b84dda496e'
down_revision: Union[str, Sequence[str], None] = '39169e78c3b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('base_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_profiles_id'), 'llm_profiles', ['id'], unique=False)
    op.drop_index(op.f('idx_critical_notification_logs_accession_no'), table_name='critical_notification_logs')
    op.create_index('idx_critical_notif_at', 'critical_notification_logs', ['notified_at'], unique=False)
    op.create_index('idx_critical_notif_case', 'critical_notification_logs', ['case_id', 'case_type'], unique=False)
    op.create_index(op.f('ix_critical_notification_logs_accession_no'), 'critical_notification_logs', ['accession_no'], unique=False)
    op.create_index(op.f('ix_critical_notification_logs_case_id'), 'critical_notification_logs', ['case_id'], unique=False)
    op.create_index(op.f('ix_critical_notification_logs_id'), 'critical_notification_logs', ['id'], unique=False)
    op.add_column('gyne_cytology_cases', sa.Column('is_out_lab', sa.Boolean(), nullable=True))
    op.alter_column('gyne_cytology_cases', 'is_express',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_gyne_cytology_cases_is_out_lab'), 'gyne_cytology_cases', ['is_out_lab'], unique=False)
    op.create_index(op.f('ix_legacy_gyne_cyto_reports_accession_no'), 'legacy_gyne_cyto_reports', ['accession_no'], unique=False)
    op.create_index(op.f('ix_legacy_gyne_cyto_reports_id'), 'legacy_gyne_cyto_reports', ['id'], unique=False)
    op.create_index(op.f('ix_legacy_gyne_cyto_reports_patient_hn'), 'legacy_gyne_cyto_reports', ['patient_hn'], unique=False)
    op.create_index(op.f('ix_legacy_gyne_cyto_reports_patient_name'), 'legacy_gyne_cyto_reports', ['patient_name'], unique=False)
    op.create_index(op.f('ix_legacy_nongyne_cyto_reports_accession_no'), 'legacy_nongyne_cyto_reports', ['accession_no'], unique=False)
    op.create_index(op.f('ix_legacy_nongyne_cyto_reports_id'), 'legacy_nongyne_cyto_reports', ['id'], unique=False)
    op.create_index(op.f('ix_legacy_nongyne_cyto_reports_patient_hn'), 'legacy_nongyne_cyto_reports', ['patient_hn'], unique=False)
    op.create_index(op.f('ix_legacy_nongyne_cyto_reports_patient_name'), 'legacy_nongyne_cyto_reports', ['patient_name'], unique=False)
    op.create_index(op.f('ix_legacy_surgical_reports_accession_no'), 'legacy_surgical_reports', ['accession_no'], unique=False)
    op.create_index(op.f('ix_legacy_surgical_reports_id'), 'legacy_surgical_reports', ['id'], unique=False)
    op.create_index(op.f('ix_legacy_surgical_reports_patient_hn'), 'legacy_surgical_reports', ['patient_hn'], unique=False)
    op.create_index(op.f('ix_legacy_surgical_reports_patient_name'), 'legacy_surgical_reports', ['patient_name'], unique=False)
    op.add_column('nongyne_cytology_cases', sa.Column('is_out_lab', sa.Boolean(), nullable=True))
    op.alter_column('nongyne_cytology_cases', 'is_pending',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('nongyne_cytology_cases', 'is_express',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_nongyne_cytology_cases_is_out_lab'), 'nongyne_cytology_cases', ['is_out_lab'], unique=False)
    op.alter_column('nongyne_report_signers', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('notification_rules', 'channel_id',
               existing_type=sa.INTEGER(),
               comment='Legacy single channel; prefer channel_ids',
               existing_comment='Which channel to notify; NULL = disabled',
               existing_nullable=True)
    op.alter_column('notification_rules', 'channel_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='List of channel IDs to notify; overrides channel_id when set',
               existing_nullable=True)
    op.add_column('system_settings', sa.Column('tumor_registry_enabled', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('system_settings', sa.Column('tumor_registry_llm_profile_id', sa.Integer(), nullable=True))
    op.add_column('system_settings', sa.Column('tumor_registry_system_prompt', sa.Text(), nullable=True))
    op.add_column('system_settings', sa.Column('show_icd_o_in_report', sa.Boolean(), nullable=False, server_default='false'))
    op.create_foreign_key(None, 'system_settings', 'llm_profiles', ['tumor_registry_llm_profile_id'], ['id'])
    op.create_foreign_key(None, 'users', 'positions', ['position_id'], ['id'])
    op.create_foreign_key(None, 'users', 'hospitals', ['hospital_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'system_settings', type_='foreignkey')
    op.drop_column('system_settings', 'show_icd_o_in_report')
    op.drop_column('system_settings', 'tumor_registry_system_prompt')
    op.drop_column('system_settings', 'tumor_registry_llm_profile_id')
    op.drop_column('system_settings', 'tumor_registry_enabled')
    op.alter_column('notification_rules', 'channel_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='List of channel IDs to notify; overrides channel_id when set',
               existing_nullable=True)
    op.alter_column('notification_rules', 'channel_id',
               existing_type=sa.INTEGER(),
               comment='Which channel to notify; NULL = disabled',
               existing_comment='Legacy single channel; prefer channel_ids',
               existing_nullable=True)
    op.alter_column('nongyne_report_signers', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_nongyne_cytology_cases_is_out_lab'), table_name='nongyne_cytology_cases')
    op.alter_column('nongyne_cytology_cases', 'is_express',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('nongyne_cytology_cases', 'is_pending',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_column('nongyne_cytology_cases', 'is_out_lab')
    op.drop_index(op.f('ix_legacy_surgical_reports_patient_name'), table_name='legacy_surgical_reports')
    op.drop_index(op.f('ix_legacy_surgical_reports_patient_hn'), table_name='legacy_surgical_reports')
    op.drop_index(op.f('ix_legacy_surgical_reports_id'), table_name='legacy_surgical_reports')
    op.drop_index(op.f('ix_legacy_surgical_reports_accession_no'), table_name='legacy_surgical_reports')
    op.drop_index(op.f('ix_legacy_nongyne_cyto_reports_patient_name'), table_name='legacy_nongyne_cyto_reports')
    op.drop_index(op.f('ix_legacy_nongyne_cyto_reports_patient_hn'), table_name='legacy_nongyne_cyto_reports')
    op.drop_index(op.f('ix_legacy_nongyne_cyto_reports_id'), table_name='legacy_nongyne_cyto_reports')
    op.drop_index(op.f('ix_legacy_nongyne_cyto_reports_accession_no'), table_name='legacy_nongyne_cyto_reports')
    op.drop_index(op.f('ix_legacy_gyne_cyto_reports_patient_name'), table_name='legacy_gyne_cyto_reports')
    op.drop_index(op.f('ix_legacy_gyne_cyto_reports_patient_hn'), table_name='legacy_gyne_cyto_reports')
    op.drop_index(op.f('ix_legacy_gyne_cyto_reports_id'), table_name='legacy_gyne_cyto_reports')
    op.drop_index(op.f('ix_legacy_gyne_cyto_reports_accession_no'), table_name='legacy_gyne_cyto_reports')
    op.drop_index(op.f('ix_gyne_cytology_cases_is_out_lab'), table_name='gyne_cytology_cases')
    op.alter_column('gyne_cytology_cases', 'is_express',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_column('gyne_cytology_cases', 'is_out_lab')
    op.drop_index(op.f('ix_critical_notification_logs_id'), table_name='critical_notification_logs')
    op.drop_index(op.f('ix_critical_notification_logs_case_id'), table_name='critical_notification_logs')
    op.drop_index(op.f('ix_critical_notification_logs_accession_no'), table_name='critical_notification_logs')
    op.drop_index('idx_critical_notif_case', table_name='critical_notification_logs')
    op.drop_index('idx_critical_notif_at', table_name='critical_notification_logs')
    op.create_index(op.f('idx_critical_notification_logs_accession_no'), 'critical_notification_logs', ['accession_no'], unique=False)
    op.drop_index(op.f('ix_llm_profiles_id'), table_name='llm_profiles')
    op.drop_table('llm_profiles')
    # ### end Alembic commands ###
