"""make molecular case parent optional and add standalone registration fields

Revision ID: d58ce869a89a
Revises: 84d42681d7e2
Create Date: 2026-07-21 11:04:07.723669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd58ce869a89a'
down_revision: Union[str, Sequence[str], None] = '84d42681d7e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('molecular_cases', sa.Column('patient_id', sa.Integer(), nullable=True))
    op.add_column('molecular_cases', sa.Column('hospital_id', sa.Integer(), nullable=True))
    op.add_column('molecular_cases', sa.Column('department_id', sa.Integer(), nullable=True))
    op.add_column('molecular_cases', sa.Column('medical_scheme_id', sa.Integer(), nullable=True))
    op.add_column('molecular_cases', sa.Column('hn', sa.String(), nullable=True))
    op.add_column('molecular_cases', sa.Column('an', sa.String(), nullable=True))
    op.add_column('molecular_cases', sa.Column('vn', sa.String(), nullable=True))
    op.add_column('molecular_cases', sa.Column('clinical_diagnosis', sa.Text(), nullable=True))
    op.add_column('molecular_cases', sa.Column('clinician_name', sa.String(), nullable=True))
    op.add_column('molecular_cases', sa.Column('collect_at', sa.DateTime(), nullable=True))
    op.alter_column('molecular_cases', 'parent_case_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_molecular_cases_hn'), 'molecular_cases', ['hn'], unique=False)
    op.create_foreign_key(None, 'molecular_cases', 'departments', ['department_id'], ['id'])
    op.create_foreign_key(None, 'molecular_cases', 'patients', ['patient_id'], ['id'])
    op.create_foreign_key(None, 'molecular_cases', 'hospitals', ['hospital_id'], ['id'])
    op.create_foreign_key(None, 'molecular_cases', 'medical_schemes', ['medical_scheme_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'molecular_cases', type_='foreignkey')
    op.drop_constraint(None, 'molecular_cases', type_='foreignkey')
    op.drop_constraint(None, 'molecular_cases', type_='foreignkey')
    op.drop_constraint(None, 'molecular_cases', type_='foreignkey')
    op.drop_index(op.f('ix_molecular_cases_hn'), table_name='molecular_cases')
    op.alter_column('molecular_cases', 'parent_case_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('molecular_cases', 'collect_at')
    op.drop_column('molecular_cases', 'clinician_name')
    op.drop_column('molecular_cases', 'clinical_diagnosis')
    op.drop_column('molecular_cases', 'vn')
    op.drop_column('molecular_cases', 'an')
    op.drop_column('molecular_cases', 'hn')
    op.drop_column('molecular_cases', 'medical_scheme_id')
    op.drop_column('molecular_cases', 'department_id')
    op.drop_column('molecular_cases', 'hospital_id')
    op.drop_column('molecular_cases', 'patient_id')
    # ### end Alembic commands ###
