"""add nongyne specimen disposal

Revision ID: d6219a67897e
Revises: 465685500204
Create Date: 2026-09-04 21:48:41.672252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6219a67897e'
down_revision: Union[str, Sequence[str], None] = '465685500204'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nongyne_specimen_disposal_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_no', sa.String(length=20), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='PRINTED', nullable=False),
    sa.Column('disposal_method', sa.String(length=200), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('printed_by_id', sa.Integer(), nullable=True),
    sa.Column('printed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('disposer_id', sa.Integer(), nullable=True),
    sa.Column('verifier_id', sa.Integer(), nullable=True),
    sa.Column('approver_id', sa.Integer(), nullable=True),
    sa.Column('disposer_name', sa.String(length=200), nullable=True),
    sa.Column('verifier_name', sa.String(length=200), nullable=True),
    sa.Column('approver_name', sa.String(length=200), nullable=True),
    sa.Column('disposed_at', sa.DateTime(), nullable=True),
    sa.Column('disposed_by_id', sa.Integer(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_by_id', sa.Integer(), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['cancelled_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['disposed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['disposer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['printed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['verifier_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nongyne_specimen_disposal_batches_batch_no'), 'nongyne_specimen_disposal_batches', ['batch_no'], unique=True)
    op.create_index(op.f('ix_nongyne_specimen_disposal_batches_id'), 'nongyne_specimen_disposal_batches', ['id'], unique=False)
    op.create_table('nongyne_specimen_disposal_batch_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['nongyne_specimen_disposal_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['case_id'], ['nongyne_cytology_cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'case_id', name='uq_ng_disposal_batch_case')
    )
    op.create_index('idx_ng_disposal_item_case', 'nongyne_specimen_disposal_batch_items', ['case_id'], unique=False)
    op.create_index(op.f('ix_nongyne_specimen_disposal_batch_items_id'), 'nongyne_specimen_disposal_batch_items', ['id'], unique=False)
    op.add_column('nongyne_cytology_cases', sa.Column('discard_status', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('nongyne_cytology_cases', sa.Column('discard_at', sa.DateTime(), nullable=True))
    op.add_column('nongyne_cytology_cases', sa.Column('discard_by_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_nongyne_cytology_cases_discard_status'), 'nongyne_cytology_cases', ['discard_status'], unique=False)
    op.create_foreign_key('fk_nongyne_cytology_cases_discard_by_id_users', 'nongyne_cytology_cases', 'users', ['discard_by_id'], ['id'])
    op.add_column('system_settings', sa.Column('nongyne_specimen_retention_days', sa.Integer(), server_default='30', nullable=False))
    op.add_column('system_settings', sa.Column('nongyne_specimen_disposal_doc_no', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_settings', 'nongyne_specimen_disposal_doc_no')
    op.drop_column('system_settings', 'nongyne_specimen_retention_days')
    op.drop_constraint('fk_nongyne_cytology_cases_discard_by_id_users', 'nongyne_cytology_cases', type_='foreignkey')
    op.drop_index(op.f('ix_nongyne_cytology_cases_discard_status'), table_name='nongyne_cytology_cases')
    op.drop_column('nongyne_cytology_cases', 'discard_by_id')
    op.drop_column('nongyne_cytology_cases', 'discard_at')
    op.drop_column('nongyne_cytology_cases', 'discard_status')
    op.drop_index(op.f('ix_nongyne_specimen_disposal_batch_items_id'), table_name='nongyne_specimen_disposal_batch_items')
    op.drop_index('idx_ng_disposal_item_case', table_name='nongyne_specimen_disposal_batch_items')
    op.drop_table('nongyne_specimen_disposal_batch_items')
    op.drop_index(op.f('ix_nongyne_specimen_disposal_batches_id'), table_name='nongyne_specimen_disposal_batches')
    op.drop_index(op.f('ix_nongyne_specimen_disposal_batches_batch_no'), table_name='nongyne_specimen_disposal_batches')
    op.drop_table('nongyne_specimen_disposal_batches')
    # ### end Alembic commands ###
