"""detect_diff_v2

Revision ID: d97d5461f521
Revises: 576a937a0ccf
Create Date: 2026-06-19 02:35:42.545935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd97d5461f521'
down_revision: Union[str, Sequence[str], None] = '576a937a0ccf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nongyne_cytology_cases', 'is_pending',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_foreign_key(None, 'users', 'hospitals', ['hospital_id'], ['id'])
    op.create_foreign_key(None, 'users', 'positions', ['position_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('nongyne_cytology_cases', 'is_pending',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
