"""add sort_order to specimen_templates

Revision ID: df6a2d115004
Revises: 06cb31f5e846
Create Date: 2026-07-03 22:30:15.892223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df6a2d115004'
down_revision: Union[str, Sequence[str], None] = '06cb31f5e846'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specimen_templates', sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('specimen_templates', 'sort_order')
    # ### end Alembic commands ###
