"""Add is_print to surgical report

Revision ID: e24970e2e79a
Revises: a7141ff51594
Create Date: 2026-03-27 14:20:59.094868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e24970e2e79a'
down_revision: Union[str, Sequence[str], None] = 'a7141ff51594'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surgical_reports', sa.Column('is_print', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surgical_reports', 'is_print')
    # ### end Alembic commands ###
