"""add he_control_slides table

Revision ID: ec9625fd6847
Revises: 7d5f343beac2
Create Date: 2026-07-27 15:13:17.532189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'ec9625fd6847'
down_revision: Union[str, Sequence[str], None] = '7d5f343beac2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('he_control_slides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('control_no', sa.String(), nullable=False),
    sa.Column('control_date', sa.Date(), nullable=False),
    sa.Column('performed_by_id', sa.Integer(), nullable=False),
    sa.Column('performed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['performed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_he_control_slides_control_date'), 'he_control_slides', ['control_date'], unique=False)
    op.create_index(op.f('ix_he_control_slides_control_no'), 'he_control_slides', ['control_no'], unique=False)
    op.create_index(op.f('ix_he_control_slides_id'), 'he_control_slides', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_he_control_slides_id'), table_name='he_control_slides')
    op.drop_index(op.f('ix_he_control_slides_control_no'), table_name='he_control_slides')
    op.drop_index(op.f('ix_he_control_slides_control_date'), table_name='he_control_slides')
    op.drop_table('he_control_slides')
    # ### end Alembic commands ###
