"""add_report_gen_system_prompt_to_system_settings

Revision ID: ee1bd1d96806
Revises: c9c753bbe9bb
Create Date: 2026-06-26 14:14:11.544836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee1bd1d96806'
down_revision: Union[str, Sequence[str], None] = 'c9c753bbe9bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_settings', sa.Column('report_gen_system_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_settings', 'report_gen_system_prompt')
    # ### end Alembic commands ###
