"""add molecular is_print and barcode_molecular_type_code

Revision ID: f4f817548bb9
Revises: 3ebce957f931
Create Date: 2026-09-14 14:23:17.768707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4f817548bb9'
down_revision: Union[str, Sequence[str], None] = '3ebce957f931'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('molecular_cases', sa.Column('is_print', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('system_settings', sa.Column('barcode_molecular_type_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_settings', 'barcode_molecular_type_code')
    op.drop_column('molecular_cases', 'is_print')
    # ### end Alembic commands ###
