"""large updates

Revision ID: fe0d079322f0
Revises: 196031ba22a0
Create Date: 2026-06-27 22:59:02.520448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe0d079322f0'
down_revision: Union[str, Sequence[str], None] = '196031ba22a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_gyne_cyto_reports_his_sent_at'), table_name='gyne_cyto_reports')
    op.drop_index(op.f('idx_nongyne_cyto_reports_his_sent_at'), table_name='nongyne_cyto_reports')
    op.create_index(op.f('ix_nongyne_cytology_cases_is_rose'), 'nongyne_cytology_cases', ['is_rose'], unique=False)
    op.drop_index(op.f('idx_surgical_reports_his_sent_at'), table_name='surgical_reports')
    op.alter_column('system_settings', 'surgical_accession_prefix',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'S'::character varying"))
    op.alter_column('system_settings', 'gyne_accession_prefix',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'C'::character varying"))
    op.alter_column('system_settings', 'nongyne_accession_prefix',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'N'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('system_settings', 'nongyne_accession_prefix',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'N'::character varying"))
    op.alter_column('system_settings', 'gyne_accession_prefix',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'C'::character varying"))
    op.alter_column('system_settings', 'surgical_accession_prefix',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'S'::character varying"))
    op.create_index(op.f('idx_surgical_reports_his_sent_at'), 'surgical_reports', ['his_sent_at'], unique=False)
    op.drop_index(op.f('ix_nongyne_cytology_cases_is_rose'), table_name='nongyne_cytology_cases')
    op.create_index(op.f('idx_nongyne_cyto_reports_his_sent_at'), 'nongyne_cyto_reports', ['his_sent_at'], unique=False)
    op.create_index(op.f('idx_gyne_cyto_reports_his_sent_at'), 'gyne_cyto_reports', ['his_sent_at'], unique=False)
    # ### end Alembic commands ###
