"""add mfa_required_since anchor

Revision ID: fe20f9e98627
Revises: 4d5dc1741ace
Create Date: 2026-08-21 09:53:11.212841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe20f9e98627'
down_revision: Union[str, Sequence[str], None] = '4d5dc1741ace'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_settings', sa.Column('mfa_required_since', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_settings', 'mfa_required_since')
    # ### end Alembic commands ###
